In [112]:
# importing libs

import pandas as pd
import numpy as np
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.preprocessing import Binarizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import Normalizer

In [113]:
# importing data from URL

url = 'https://raw.githubusercontent.com/akaakselabhijeet/Data-Science-Datasets-Ver.01/main/India_Data/India%20Election%20Dataset%201.csv'
ls = pd.read_csv(url)
print(ls.head(5))
ls.info()

           State Constituency  ... VotePercent  TotalElectors
0      Telangana     ADILABAD  ...   35.468248        1489790
1      Telangana     ADILABAD  ...   29.964370        1489790
2      Telangana     ADILABAD  ...   29.534285        1489790
3      Telangana     ADILABAD  ...    1.225214        1489790
4  Uttar Pradesh         AGRA  ...   56.464615        1937690

[5 rows x 19 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2263 entries, 0 to 2262
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   State            2263 non-null   object 
 1   Constituency     2263 non-null   object 
 2   Name             2263 non-null   object 
 3   Winner           2263 non-null   int64  
 4   Party            2263 non-null   object 
 5   Symbol           2018 non-null   object 
 6   Gender           2018 non-null   object 
 7   CriminalCases    2018 non-null   object 
 8   Age              2018 non-null   

In [114]:
# make a clone

ls1 = ls.copy()
print(ls1.head(4))

       State Constituency  ... VotePercent  TotalElectors
0  Telangana     ADILABAD  ...   35.468248        1489790
1  Telangana     ADILABAD  ...   29.964370        1489790
2  Telangana     ADILABAD  ...   29.534285        1489790
3  Telangana     ADILABAD  ...    1.225214        1489790

[4 rows x 19 columns]


In [115]:
# Applying discretizer on GenVotes

discretizer = KBinsDiscretizer()
discretizer = discretizer.fit_transform(ls1['GenVotes'].values.reshape(-1,1))
print(discretizer)

  (0, 3)	1.0
  (1, 2)	1.0
  (2, 2)	1.0
  (3, 0)	1.0
  (4, 4)	1.0
  (5, 3)	1.0
  (6, 1)	1.0
  (7, 4)	1.0
  (8, 3)	1.0
  (9, 1)	1.0
  (10, 4)	1.0
  (11, 2)	1.0
  (12, 4)	1.0
  (13, 2)	1.0
  (14, 0)	1.0
  (15, 0)	1.0
  (16, 4)	1.0
  (17, 3)	1.0
  (18, 0)	1.0
  (19, 0)	1.0
  (20, 4)	1.0
  (21, 2)	1.0
  (22, 2)	1.0
  (23, 4)	1.0
  (24, 2)	1.0
  :	:
  (2238, 2)	1.0
  (2239, 2)	1.0
  (2240, 1)	1.0
  (2241, 1)	1.0
  (2242, 0)	1.0
  (2243, 4)	1.0
  (2244, 3)	1.0
  (2245, 1)	1.0
  (2246, 1)	1.0
  (2247, 4)	1.0
  (2248, 2)	1.0
  (2249, 2)	1.0
  (2250, 4)	1.0
  (2251, 2)	1.0
  (2252, 2)	1.0
  (2253, 4)	1.0
  (2254, 3)	1.0
  (2255, 2)	1.0
  (2256, 1)	1.0
  (2257, 1)	1.0
  (2258, 0)	1.0
  (2259, 3)	1.0
  (2260, 3)	1.0
  (2261, 2)	1.0
  (2262, 0)	1.0


In [116]:
# To_Array

disc1 = pd.DataFrame(discretizer.toarray(), columns=['binary_'+str(i) for i in range(1, 6)])
print(disc1.head(6))
disc1.info()

   binary_1  binary_2  binary_3  binary_4  binary_5
0       0.0       0.0       0.0       1.0       0.0
1       0.0       0.0       1.0       0.0       0.0
2       0.0       0.0       1.0       0.0       0.0
3       1.0       0.0       0.0       0.0       0.0
4       0.0       0.0       0.0       0.0       1.0
5       0.0       0.0       0.0       1.0       0.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2263 entries, 0 to 2262
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   binary_1  2263 non-null   float64
 1   binary_2  2263 non-null   float64
 2   binary_3  2263 non-null   float64
 3   binary_4  2263 non-null   float64
 4   binary_5  2263 non-null   float64
dtypes: float64(5)
memory usage: 88.5 KB


In [117]:
# Implementing Binarizer

binarizer = Binarizer(threshold = 30000)
binarizer = binarizer.fit_transform(ls1['TotalVotes'].values.reshape(-1,1))
print(binarizer)

[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [0]]


In [118]:
# new_dataframe

bin2 = pd.DataFrame(binarizer, columns=['TotalVotesBin'])
print(bin2.head(4))
print(bin2.tail(4))

   TotalVotesBin
0              1
1              1
2              1
3              0
      TotalVotesBin
2259              1
2260              1
2261              1
2262              0


In [119]:
# concat function on disc1, bin2, ls1

ls2 = pd.concat([disc1, bin2, ls1], axis=1)
print(ls2.head(6))

   binary_1  binary_2  binary_3  ...  ElectorsPercent  VotePercent  TotalElectors
0       0.0       0.0       0.0  ...        25.330684    35.468248        1489790
1       0.0       0.0       1.0  ...        21.399929    29.964370        1489790
2       0.0       0.0       1.0  ...        21.092771    29.534285        1489790
3       1.0       0.0       0.0  ...         0.875023     1.225214        1489790
4       0.0       0.0       0.0  ...        33.383823    56.464615        1937690
5       0.0       0.0       0.0  ...        22.466390    37.999125        1937690

[6 rows x 25 columns]


In [120]:
# Dataframe without 'Winner'

a1 = ls2.drop('Winner', axis=1)
print(a1.head(6))

   binary_1  binary_2  binary_3  ...  ElectorsPercent  VotePercent  TotalElectors
0       0.0       0.0       0.0  ...        25.330684    35.468248        1489790
1       0.0       0.0       1.0  ...        21.399929    29.964370        1489790
2       0.0       0.0       1.0  ...        21.092771    29.534285        1489790
3       1.0       0.0       0.0  ...         0.875023     1.225214        1489790
4       0.0       0.0       0.0  ...        33.383823    56.464615        1937690
5       0.0       0.0       0.0  ...        22.466390    37.999125        1937690

[6 rows x 24 columns]


In [121]:
# Dataframe with 'Winner'

a2 = pd.DataFrame(ls2['Winner'])
print(a2.tail(6))

      Winner
2257       0
2258       0
2259       1
2260       0
2261       0
2262       0


In [122]:
# Splitting the data in a1 and a2 in training and test data using train_test_split

X_train, X_test, y_train, y_test = train_test_split(a1, a2, test_size=0.15)
print("operation successful!")

operation successful!


In [123]:
# Implementing Standardization with RobustScaler

rscaler = RobustScaler(quantile_range=(0.25, 0.75))
rscaler = rscaler.fit_transform(a1['Age'].values.reshape(-1, 1))
print(rscaler)

[[ 0.        ]
 [ 1.84331797]
 [ 0.        ]
 ...
 [-2.76497696]
 [-4.60829493]
 [        nan]]


In [124]:
# result data into dataframe scaler1

scaler1 = pd.DataFrame(rscaler, columns=['Scaled_Age'])
print(scaler1.head(6))

   Scaled_Age
0    0.000000
1    1.843318
2    0.000000
3         NaN
4    5.529954
5   -4.608295


In [125]:
# a2 copy with selected clone

a2 = a1[['GenVotes', 'PostalVotes', 'TotalVotes']].copy()
print(a2.head(6))

   GenVotes  PostalVotes  TotalVotes
0    376892          482      377374
1    318665          149      318814
2    314057          181      314238
3     13030            6       13036
4    644459         2416      646875
5    434199         1130      435329


In [126]:
# Implementing Normalization with Normalizer(norm='max') on a2

normalizer = Normalizer(norm='max')
normalizer = normalizer.fit_transform(a2)
print(normalizer)

[[9.98722752e-01 1.27724751e-03 1.00000000e+00]
 [9.99532643e-01 4.67357142e-04 1.00000000e+00]
 [9.99424003e-01 5.75996538e-04 1.00000000e+00]
 ...
 [9.99731318e-01 2.68682172e-04 1.00000000e+00]
 [9.98445450e-01 1.55454958e-03 1.00000000e+00]
 [9.99820467e-01 1.79533214e-04 1.00000000e+00]]


In [127]:
# result data in dataframe 'normal2'

normal2 = pd.DataFrame(normalizer, columns=a2.columns)
print(normal2.head(8))

   GenVotes  PostalVotes  TotalVotes
0  0.998723     0.001277         1.0
1  0.999533     0.000467         1.0
2  0.999424     0.000576         1.0
3  0.999540     0.000460         1.0
4  0.996265     0.003735         1.0
5  0.997404     0.002596         1.0
6  0.993976     0.006024         1.0
7  0.989074     0.010926         1.0


In [128]:
# THE END
# Abhijeet Das - DS Assignment 8