In [31]:
#LAB Assignment 4 - Data Science
#Date- 06.04.2021

import numpy as np
import pandas as pd

In [32]:
#1 Np Array 1-12. In 3x4 Mat.
a1 = np.arange(1,13)
a1 = a1.reshape((3,4))
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
#1 Np Array 13-24. In 3x4 Mat.
a2 = np.arange(13,25)
a2 = a2.reshape((3,4))
print(a2)

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [34]:
#Vstack/Hstack for a1, a2:
np.vstack((a1, a2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [35]:
np.hstack((a1, a2))

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [36]:
#Q4 ...

a3 = np.copy(a1)[0]
a4 = np.copy(a1)[1]
a5 = np.copy(a1)[2]

a3[0] = 99
print(a1)
print(a3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4]


In [37]:
#Q5 ...

print("Max element in a2: {}\n".format(np.max(a2)))
print("Min element in a2: {}\n".format(np.min(a2)))
print("Max element in a2: {}\n".format(a2.transpose()))

Max element in a2: 24

Min element in a2: 13

Max element in a2: [[13 17 21]
 [14 18 22]
 [15 19 23]
 [16 20 24]]



In [38]:
#Q6 ...

np.add(a1,a2)

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [40]:
#Q7 / Q8

url = "https://raw.githubusercontent.com/akaakselabhijeet/Data-Science-Datasets-Ver.01/main/India_Data/India%20Election%20Dataset%201.csv"
df = pd.read_csv(url)
print(df.head(10))


           State Constituency  ... VotePercent  TotalElectors
0      Telangana     ADILABAD  ...   35.468248        1489790
1      Telangana     ADILABAD  ...   29.964370        1489790
2      Telangana     ADILABAD  ...   29.534285        1489790
3      Telangana     ADILABAD  ...    1.225214        1489790
4  Uttar Pradesh         AGRA  ...   56.464615        1937690
5  Uttar Pradesh         AGRA  ...   37.999125        1937690
6  Uttar Pradesh         AGRA  ...    3.940979        1937690
7    Maharashtra   AHMADNAGAR  ...   58.425159        1861396
8    Maharashtra   AHMADNAGAR  ...   35.087431        1861396
9    Maharashtra   AHMADNAGAR  ...    2.637200        1861396

[10 rows x 19 columns]


In [41]:
print(df.tail(10))

            State     Constituency  ... VotePercent  TotalElectors
2253  Maharashtra  YAVATMAL-WASHIM  ...   46.142912        1916185
2254  Maharashtra  YAVATMAL-WASHIM  ...   36.104046        1916185
2255  Maharashtra  YAVATMAL-WASHIM  ...    8.020606        1916185
2256  Maharashtra  YAVATMAL-WASHIM  ...    2.085334        1916185
2257  Maharashtra  YAVATMAL-WASHIM  ...    1.755157        1916185
2258  Maharashtra  YAVATMAL-WASHIM  ...    1.250060        1916185
2259    Telangana        ZAHIRABAD  ...   41.574183        1498666
2260    Telangana        ZAHIRABAD  ...   40.977823        1498666
2261    Telangana        ZAHIRABAD  ...   13.302678        1498666
2262    Telangana        ZAHIRABAD  ...    1.066535        1498666

[10 rows x 19 columns]


In [42]:
#Q9

df = df.sort_values('Age')
print(df.head(20))

               State     Constituency  ... VotePercent  TotalElectors
1789     West Bengal         RANAGHAT  ...   37.030315        1762252
1952       Jharkhand        SINGHBHUM  ...    1.284570        1269917
1132          Odisha         KEONJHAR  ...   44.740195        1516688
1848           Bihar  SAMASTIPUR (SC)  ...    1.384036        1679030
681     Chhattisgarh             DURG  ...    1.444943        1940269
1502      Tamil Nadu     NAGAPATTINAM  ...    5.129821        1303649
2186           Bihar         VAISHALI  ...    2.558453        1735983
138   Andhra Pradesh            ARUKU  ...   52.139840        1451418
269        Rajasthan         BANSWARA  ...    1.029228        1975368
880          Haryana            HISAR  ...   15.599664        1631817
1281       Jharkhand        LOHARDAGA  ...    1.178322        1234286
2028           Bihar           SUPAUL  ...    1.828989        1690620
1192           Assam        KOKRAJHAR  ...    1.900869        1776358
514       Tamil Nadu

In [43]:
#Q10 Print the data stats

df.describe()

Winner          Age  ...  VotePercent  TotalElectors
count  2263.000000  2018.000000  ...  2263.000000   2.263000e+03
mean      0.238179    52.273538  ...    23.190525   1.658016e+06
std       0.426064    11.869373  ...    21.564758   3.145187e+05
min       0.000000    25.000000  ...     1.000039   5.518900e+04
25%       0.000000    43.250000  ...     1.899502   1.530014e+06
50%       0.000000    52.000000  ...    16.221721   1.679030e+06
75%       0.000000    61.000000  ...    42.590233   1.816857e+06
max       1.000000    86.000000  ...    74.411856   3.150313e+06

[8 rows x 8 columns]

In [44]:
#Q11

df2 = df[df['Age']>60]
print(df2)

                State     Constituency  ... VotePercent  TotalElectors
300       West Bengal  BARDHAMAN PURBA  ...   38.310770        1698089
299       West Bengal  BARDHAMAN PURBA  ...   44.514634        1698089
1218           Odisha          KORAPUT  ...    3.309431        1434384
1544      Maharashtra        NANDURBAR  ...   42.311213        1871099
1970       Tamil Nadu        SIVAGANGA  ...   21.555785        1552019
...               ...              ...  ...         ...            ...
797         Jharkhand            GODDA  ...    1.377829        1716766
939            Punjab        JALANDHAR  ...   35.925046        1617018
2006  Jammu & Kashmir         SRINAGAR  ...   57.127414        1294671
1855    Uttar Pradesh          SAMBHAL  ...   55.584784        1828764
2137        Karnataka           TUMKUR  ...   46.792654        1608545

[554 rows x 19 columns]


In [45]:
#Q12

df1 = df[['Age', 'Gender']]
df1.head(5)

Age  Gender
1789  25.0  FEMALE
1952  25.0    MALE
1132  25.0  FEMALE
1848  25.0  FEMALE
681   25.0  FEMALE

In [ ]:
#THE END